# Use this playbook when building locally.

site:
  title: Metadata Assertion
  start_page: metadata::index.adoc
content:
  sources: 
  - url: .
    branches: HEAD
    tags:
    - v1.0
    - v1.1-final
    start_path: docs

ui:
  bundle:
    url: https://cawg.io/antora-ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./custom-ui/

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
