[appendix]
== Use with media industry identifiers

_This section is non-normative._

_(TO DO: Extract a portion of this to normative language.)_

A commercial work of art (recorded music, motion picture, etc.) may have a large number of contributors who should be identified as contributors to a single C2PA asset.
Various media industries have well-established identifiers for various individual talent professionals (musicians, actors, directors, etc.), organizations (e.g. ___), and content (e.g. motion picture releases or individual recorded audio tracks).

_(TO DO: How to specify that an actor performed a specific role? May not be feasible with existing Dublin Core mechanism. Possible there is no extant standard for more nuanced role descriptions.)_

It is often not feasible to have each individual contributor generate their own _link:https://cawg.io/identity/[identity assertion]_ both because:
. It is often not logistically feasible to have individual contributors involved in the content signing process, and
. These identifiers are often not provisioned with corresponding private key materials for signing purposes.

The CAWG recommends that such identifiers be described as follows:

. Place recognized industry identifiers in existing IETF-issued namespace and field names.
_(TO DO: Need link to registry of metadata namespace names.)_
Some examples of relevant namespaces and fields include:
.. link:++https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-3++[Dublin Core elements namespace], typically prefixed as `dc`:
... link:https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/contributor/[`dc:contributor`] - An entity responsible for making contributions to the resource.
... link:https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/creator/[`dc:creator`] - An entity primarily responsible for making the resource.
... link:https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/publisher/[`dc:publisher`] - An entity responsible for making the resource available.
.. _(TO DO: Are there other namespaces that are relevant for specific media segments?)_
. Use a CAWG _link:https://cawg.io/identity[identity assertion]_ as described in xref:_use_with_identity_assertion[xrefstyle=full], signed by a trusted industry entity to vouch for the validity of the identifiers in the *metadata assertion.*
A trusted industry entity in this context means an entity, such as a registrar or media packager, that is trusted within the industry to accurately record the identifiers in question.

=== Examples

The following is an example of the CAWG metadata assertion using globally-unique, standards-based identifiers that can be freely resolved by visiting the link:https://www.doi.org[Digital Object Identifier (DOI) Foundation] web site to obtain additional authoritative information about the media asset.

[[person-identifier-example]]
[source,json]
.Example of a CAWG metadata assertion (DRAFT with EIDR and HAND identifiers)
----
{
   "@context" : {
        "dc" : "http://purl.org/dc/elements/1.1/",
   },
   "dc:contributor" : ["Edwin Stanton Porter", "urn:doi:10.23/EF98-D5B3-1931-90A8-F50C"],
   "dc:identifier" : ["The Great Train Robbery", "urn:eidr:10.5240/7791-8534-2C23-9030-8610-5"],
   "dc:title" : "TO DO",
   "dc:description" : "TO DO",
   "dc:publisher" : "...",
   "dc:date" : "1903-12-01",
   "dc:type" : "Image",
}
----
